spring:
  application:
    name: EmployeeApp
#  datasource:
#    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/employeeDB
#    username: ${MYSQL_USER:emp_user}
#    password: ${MYSQL_PASSWORD:emp_pw}
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    com:
      app:
        employee: DEBUG
server:
  port: 8080