spring:
  application:
    name: employee-app
  datasource:
    url: jdbc:h2:mem:employeeDB
    driverClassName: org.h2.Driver
    username: ${MYSQL_USER:sa}
    password: ${MYSQL_PASSWORD:}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    com:
      app:
        employee: DEBUG
server:
  port: 8080